### ISSUE TITLE
EGLPlayerActivity 好像无法正常播放了

### ISSUE THREAD

**Issue by lwlizhe** [ChenLittlePing/LearningVideo#11]
现在播放视频是一直黑屏的……

看了下代码，好像是render的时候mRenderMode = RenderMode.RENDER_WHEN_DIRTY，所以执行holdOn方法让其进入等待状态，但是后续并无方法调用notify方法通知唤醒，所以thread一直等待，无法绘制上屏……

不知道是不是这个原因，我也是刚刚开始学这块，可能不对……总之希望大佬修复下

**Comment by lwlizhe** [comment]
额，我这注释掉那个holdOn方法，同时将render方法中的if(render) 改为 if(true) 强制绘制后能正常播放了……
如果有人需要的话可以先这么弄

**Comment by ChenLittlePing** [comment]
@lwlizhe 确实是你说的那样，因为mRenderMode = RenderMode.RENDER_WHEN_DIRTY，又没有地方通知渲染线程重新渲染，导致一直等待。
最新代码已经加入了解码帧监听，动态通知渲染。[点击查看修改的地方](https://github.com/ChenLittlePing/LearningVideo/commit/68345e4b3749ca6dc5dc2684dbc75e2998f857b1)
也可以把 RenderMode 设置为 RENDER_CONTINUOUSLY ，开启自动循环渲染。

**Comment by lwlizhe** [comment]
@ChenLittlePing 大佬给力，点个赞
